links = {
    'epl_links': {'pin': "https://www.pinnacle.com/en/soccer/england-premier-league/matchups/#all",
           'sb': 'https://www.sportsbet.com.au/betting/soccer/united-kingdom/english-premier-league',
           'tab': 'https://www.tab.com.au/sports/betting/Soccer/competitions/English%20Premier%20League'},
    'eng_champ': {'pin': 'https://www.pinnacle.com/en/soccer/england-championship/matchups/#all',
                  'tab': 'https://www.tab.com.au/sports/betting/Soccer/competitions/English%20Championship',
                  'sb': 'https://www.sportsbet.com.au/betting/soccer/united-kingdom/english-championship'},
    'bundesliga': {'pin': 'https://www.pinnacle.com/en/soccer/germany-bundesliga/matchups/#all',
                   'tab': 'https://www.tab.com.au/sports/betting/Soccer/competitions/German%20Bundesliga',
                   'sb': 'https://www.sportsbet.com.au/betting/soccer/germany/german-bundesliga'},
    'serie-a': {'pin': 'https://www.pinnacle.com/en/soccer/italy-serie-a/matchups/#all',
                'tab': 'https://www.tab.com.au/sports/betting/Soccer/competitions/Italian%20Serie%20A',
                'sb': 'https://www.sportsbet.com.au/betting/soccer/italy/italian-serie-a'},
    'laliga': {'pin': 'https://www.pinnacle.com/en/soccer/spain-la-liga/matchups/#all',
               'tab': 'https://www.tab.com.au/sports/betting/Soccer/competitions/Spanish%20Primera%20Division',
               'sb': 'https://www.sportsbet.com.au/betting/soccer/spain/spanish-la-liga'},
    'nrl_links': {'pin': 'https://www.pinnacle.com/en/rugby-league/nrl/matchups/#period:0',
           'sb': 'https://www.sportsbet.com.au/betting/rugby-league/nrl',
           'tab': 'https://www.tab.com.au/sports/betting/Rugby%20League/competitions/NRL'},
    'afl_links': {'pin': 'https://www.pinnacle.com/en/aussie-rules/aussie-rules-football-afl/matchups/#period:0',
           'sb': 'https://www.sportsbet.com.au/betting/australian-rules/afl',
           'tab': 'https://www.tab.com.au/sports/betting/AFL%20Football'}
}